### ISSUE TITLE
Add a gallery page

### ISSUE THREAD

**Issue by NishikantaRay** [NishikantaRay/Rawsome-Photography#6]

**Comment by nitin-pandita** [comment]
Can i get some more details about the issue and can i try this ?

**Comment by NishikantaRay** [comment]
https://youtu.be/U-CujW5OlW0   I need this type of gallery with pop up view

**Comment by nitin-pandita** [comment]
> https://youtu.be/U-CujW5OlW0 I need this type of gallery with pop up view

sure , if you like i get started with this

**Comment by nitin-pandita** [comment]
I am little confused , the thing that you want is already in their so what  is the feature that you actually want ?
